### ISSUE TITLE
"Outside" lines in 58.4.4b

### ISSUE THREAD

**Issue by okudy** [lucymerobinson/CCAMLRGIS#30] opened 2018-08-17 08:01 UTC
When I get Research Blocks from CCAMLRGIS using the following code, there are several lines "Outside" of the research block.

HAUL<-read.csv("CCAMLR_C2_Effort.csv")
newproj<- "+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0"
Research_Blocks <- load_RBs(format = "GEOJSON")
Research_Blocks <- spTransform(Research_Blocks, CRS(newproj))
HAUL_spatial <- SpatialPoints(HAUL[,c("LONGITUDE_START_SET","LATITUDE_START_SET")], proj4string=CRS(newproj),bbox=NULL)
HAUL$Research_Block_Over <- over(HAUL_spatial, Research_Blocks)$GAR_Short_Label
HAUL$Research_Block_Over<-factor(HAUL$Research_Block_Over, levels = c(Research_Blocks_in_order,"Outside"))
HAUL$Research_Block_Over[is.na(HAUL$Research_Block_Over)] <- "Outside"

I'm wondering that the boundary of research blocks recorded in CCAMLRGIS is different from the boundary actually used when the vessel operates.

**Comment by lucymerobinson** [comment] 2018-08-22 09:38
The R package is just reading data from an online spatial data repository so it doesn’t sound like an issue with the R code. Have you checked that the coordinates your vessels are using agree with the coordinates of the polygons provided through the CCAMLRGIS? Also worth checking with Keith about the historical buffer zones around Research Blocks. Otherwise there could be issues with the positions of the C2 haul data.

**Comment by KeithReid** [comment] 2018-08-23 09:06
Hi  - as Lucy suggested the issue is probably with the definition of the polygon in the CCAMLR data repository.  Tim is investigating and will be in contact with Japan and France to resolve the RB boundaries.  Once this is addressed  the 'points outside' issue should go away.

**Closed** 2019-12-04 00:04 UTC
